services:
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:7.8
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres


  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    ports:
      - 8081:8080
    depends_on:
      - "postgres"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

    command: 
      - start-dev --db=postgres